name: Test Neovim Config in Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Neovim and Dependencies
      run: |
        sudo apt update
        sudo apt install -y neovim ripgrep fzf
        # Hier installierst du alles, was du für deine Konfiguration benötigst.
        
    - name: Setup Neovim Configuration
      run: |
        rm -rf ~/.config/nvim
        mkdir -p ~/.config/nvim
        git clone https://github.com/Fiko767/test.git ~/.config/nvim
        
    - name: Install Plugins using lazy.nvim
      run: |
        nvim --headless +LazyInstall +qall

    - name: Set up Cloud VM and Web Access (z.B. noVNC)
      run: |
        # Hier startet GitHub Actions eine Cloud-VM mit einer Weboberfläche.
        # Setzt z.B. noVNC oder einen Webserver für den Zugriff auf Neovim auf.

    - name: Provide URL to Access Neovim in Browser
      run: |
        echo "Neovim is available at: https://your-cloud-instance-url"
