name: Test Neovim Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Neovim
      run: |
        sudo apt update
        sudo apt install -y neovim

    - name: Install dependencies
      run: |
        # Install any additional dependencies your config needs
        sudo apt install -y ripgrep fzf

    - name: Open Neovim
      run: |
        # Öffne Neovim ohne headless Mode, damit es offen bleibt
        nohup nvim &
