name: Test Neovim Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Neovim
      run: |
        sudo apt update
        sudo apt install -y neovim

    - name: Install dependencies
      run: |
        # Install any additional dependencies your config needs
        sudo apt install -y ripgrep fzf

    - name: Set up Neovim configuration
      run: |
        # Lösche das Standard-Neovim-Konfigurationsverzeichnis (falls es existiert)
        rm -rf ~/.config/nvim
        
        # Kopiere die Konfiguration aus dem Repository
        mkdir -p ~/.config/nvim
        cp -r ./path/to/your/nvim/config/* ~/.config/nvim/

    - name: Install Neovim Plugins
      run: |
        # Wenn du ein Plugin-Manager wie 'vim-plug' oder 'packer' verwendest
        nvim --headless +PlugInstall +qall  # Für vim-plug
        # oder
        # nvim --headless +PackerSync +qall  # Für Packer

    - name: Test Neovim configuration
      run: |
        # Teste die Konfiguration, indem Neovim im headless Mode läuft
        nvim --headless -c 'qa!'  # Schließt Neovim sofort ohne Interaktion

