name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v2

      - name: Abhängigkeiten installieren
        run: |
          rm -rf ~/.config/nvim
          git clone https://github.com/Fiko767/test.git ~/.config/nvim

      - name: Befehl ausführen
        run: |
          # Ersetze 'dein_befehl' mit dem tatsächlichen Befehl, den du ausführen möchtest
          nvim
